# GLOBAL SITE SETTINGS

cname: dannybeaton.yourwebvisual.com

# META
title: Danny Beaton
title_homepage: The Official Danny Beaton Website - Mal Winter and the Cloud Runners
company: Danny Beaton
description: Danny Beaton is ready to take preorders on his new book, Mal Winter and the Last Titan

# SITE DEFAULTS
site_tagline:

# DEVELOPER
allow_robots: false
github_repo_owner: liquidvisual
github_repo_path: https://github.com/liquidvisual/2017.dannybeaton.com.au
github_repo_name: 2017.dannybeaton.com.au
jekyll_version: 3.0.3

# OFFICES
offices:
  - title:
    address:

# SOCIAL MEDIA
facebook: https://facebook.com/dannybeatonwriter
twitter: https://twitter.com/DannyBeaton
linked_in:
google_plus:
instagram: http://instagram.com/dannybeaton
youtube: https://www.youtube.com/channel/UC4S74VhUhaL1HGv3kxYyH6Q

# GOOGLE
google_analytics: "UA-52532977-1"

# AUTHOR
author:
  title: Mitch
  url: http://liquidvisual.com
  logo: /assets/img/ui/liquidvisual-logo-dark1.svg
  description: liquidvisual